### ISSUE TITLE
Issue on WiX.Toolset.NuGet Repository

### ISSUE THREAD

**Issue by RobertK66** [jozefizso/ReSharper.WixToolset#1]
Hi @jozefizso , 
I am sorry to misuse this repo, because in your jozefizso/WiX.Toolset.NuGet repo there is no Issue folder available. As you invite everybody there to do so I file it here:
 ... copied  to  https://github.com/jozefizso/WiX.Toolset.NuGet/issues/1 ...

**Comment by jozefizso** [comment]
I've enabled issues tracking for that repository. Can you post the issue there? https://github.com/jozefizso/WiX.Toolset.NuGet/issues

Do you have Fusion Binding logs? They are very helpful for troubleshooting .NET assembly references.

Thanks.

**Comment by RobertK66** [comment]
Wow you are fast :-D
I copied it.

**Comment by jozefizso** [comment]
Moved to https://github.com/jozefizso/WiX.Toolset.NuGet/issues/1
